avro_blog_comment:
    resource: "@AvroBlogBundle/Controller/CommentController.php"
    type:     annotation 
 
avro_blog_admin:
    resource: "@AvroBlogBundle/Controller/AdminController.php"
    type:     annotation 
 
avro_blog_post:
    resource: "@AvroBlogBundle/Controller/PostController.php"
    type:     annotation 

avro_blog_blog:
    resource: "@AvroBlogBundle/Controller/BlogController.php"
    type:     annotation 


